- Mary Flanagan - [domestic] - 2003
- Anna Anthropy - Dys4ia - 2012
- Zoe Quinn - Depression Quest - 2013
- Nina Freeman - How do you do it - 2014
- Nina Freeman - Cibele - 2015
- Ryan Green et Josh Larson - That Dragon, Cancer - 2016
- Cassie Mc Quater - Black Room - 2017 
- Tabitha Nikolai - Ineffable Glossolalia - 2018
- Amanda Kirk - Gardening in the rain during Naptime - 2018 
- Juno Morrow - Conspiracy Theories about myself - 2018
- Carol Mertz - I’ll here - 2019
- Sébastien Genvo - Lie in my heart - 2019 
- Nina Freeman - We Met in May - 2019 
- Juno Morrow - Laundry++ - 2019
- Nina Freeman - Last Call - 2021
- Dr Skinquifer - Second Puberty - 2021
- Tinrey Wang - The Third Person and I - 2022
- Taylor McCue - He fucked the girl out of me - 2022
